json.id resource.id
json.world_region resource.world_region
json.title resource.title
json.author resource.author
json.news_source resource.news_source
json.date resource.date
json.summary resource.summary
json.url resource.url
json.notes resource.notes
json.created_at resource.created_at
json.updated_at resource.updated_at
